apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 261273955683.dkr.ecr.us-east-1.amazonaws.com/bookstore-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: AWS_REGION
              value: "us-east-1"
            - name: NODE_ENV
              value: "development"
            - name: AWS_ACCESS_KEY_ID
              value: "TU_ACCESS_KEY_ID"
            - name: AWS_SECRET_ACCESS_KEY
              value: "TU_SECRET_ACCESS_KEY"
            - name: AWS_SESSION_TOKEN
              value: "TU_SESSION_TOKEN"