# ============================================================
# Configuración del clúster EKS - Bookstore
# Usa tu VPC existente (proyecto-vpc)
#
# USO: eksctl create cluster -f cluster-config.yaml
# ============================================================

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bookstore-cluster
  region: us-east-1
  version: "1.29"

# ── VPC existente ──
# En lugar de crear una VPC nueva, usamos la tuya
vpc:
  id: vpc-0cc2802a22f4774fc
  subnets:
    public:
      us-east-1a:
        id: subnet-00d5074287dfba932    # proyecto-subnet-public1-us-east-1a
      us-east-1b:
        id: subnet-0823668c6cdd8a324    # proyecto-subnet-public2-us-east-1b
    private:
      us-east-1a:
        id: subnet-04688d6354f2aef22    # proyecto-subnet-private1-us-east-1a
      us-east-1b:
        id: subnet-0915ff1a9b1241696    # proyecto-subnet-private2-us-east-1b

# ── Nodos worker ──
# Van en las subnets privadas por seguridad
managedNodeGroups:
  - name: bookstore-nodes
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: true             # nodos en subnets privadas
    subnets:
      - subnet-04688d6354f2aef22        # private1 us-east-1a
      - subnet-0915ff1a9b1241696        # private2 us-east-1b
    iam:
      withAddonPolicies:
        imageBuilder: true              # permite pull de ECR
        autoScaler: true

# ── OIDC para IRSA ──
# Necesario para que los pods asuman IAM Roles (DynamoDB)
iam:
  withOIDC: true
