apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 261273955683.dkr.ecr.us-east-1.amazonaws.com/bookstore-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: NGINX_PORT
              value: "80"
            - name: BOOKS_SERVICE_URL
              value: "http://books-service:5001"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:5002"
            - name: REVIEWS_SERVICE_URL
              value: "http://reviews-service:5003"
