apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-service
  template:
    metadata:
      labels:
        app: books-service
    spec:
      containers:
        - name: books-service
          image: 261273955683.dkr.ecr.us-east-1.amazonaws.com/bookstore-books-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: NODE_ENV
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SESSION_TOKEN
            - name: DYNAMO_TABLE
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: DYNAMO_TABLE
