apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/bookstore-auth-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: NODE_ENV
              value: "production"
