```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  MyBookStore — Stack 05: EKS Cluster
  Cluster Kubernetes usando LabRole (AWS Academy).

Parameters:
  ProjectName:
    Type: String
    Default: bookstore

  KubernetesVersion:
    Type: String
    Default: "1.29"

  NodeInstanceType:
    Type: String
    Default: t3.medium

  NodeMinSize:
    Type: Number
    Default: 2

  NodeMaxSize:
    Type: Number
    Default: 4

  NodeDesiredSize:
    Type: Number
    Default: 2

Resources:

  # ── Cluster EKS ──
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Sub "${ProjectName}-cluster"
      Version: !Ref KubernetesVersion

      RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"

      ResourcesVpcConfig:
        SubnetIds:
          - !ImportValue
              Fn::Sub: "${ProjectName}-PrivateSubnetAZ1Id"
          - !ImportValue
              Fn::Sub: "${ProjectName}-PrivateSubnetAZ2Id"
          - !ImportValue
              Fn::Sub: "${ProjectName}-PublicSubnetAZ1Id"
          - !ImportValue
              Fn::Sub: "${ProjectName}-PublicSubnetAZ2Id"

        SecurityGroupIds:
          - !ImportValue
              Fn::Sub: "${ProjectName}-SGEksId"

        EndpointPublicAccess: true
        EndpointPrivateAccess: true

  # ── Node Group ──
  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref EKSCluster

      NodegroupName: !Sub "${ProjectName}-node-group"

      NodeRole: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"

      InstanceTypes:
        - !Ref NodeInstanceType

      ScalingConfig:
        MinSize: !Ref NodeMinSize
        MaxSize: !Ref NodeMaxSize
        DesiredSize: !Ref NodeDesiredSize

      Subnets:
        - !ImportValue
            Fn::Sub: "${ProjectName}-PrivateSubnetAZ1Id"
        - !ImportValue
            Fn::Sub: "${ProjectName}-PrivateSubnetAZ2Id"

      Labels:
        project: !Ref ProjectName

Outputs:
  ClusterName:
    Value: !Ref EKSCluster
    Export:
      Name: !Sub "${ProjectName}-ClusterName"

  ClusterEndpoint:
    Value: !GetAtt EKSCluster.Endpoint
    Export:
      Name: !Sub "${ProjectName}-ClusterEndpoint"

  ClusterArn:
    Value: !GetAtt EKSCluster.Arn
    Export:
      Name: !Sub "${ProjectName}-ClusterArn"
```
