AWSTemplateFormatVersion: "2010-09-09"
Description: >
  MyBookStore - Stack 06: S3 Buckets
  Bucket de objetos (portadas de libros) y bucket frontend (React build).

Parameters:
  ProjectName:
    Type: String
    Default: bookstore

Resources:

  # Bucket de objetos - portadas de libros
  ObjectsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-objects-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET]
            AllowedOrigins: ["*"]
            AllowedHeaders: ["*"]
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Sub "${ProjectName}-objects"

  # Bucket frontend - React build estatico
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Sub "${ProjectName}-frontend"

Outputs:
  ObjectsBucketName:
    Value: !Ref ObjectsBucket
    Export:
      Name: !Sub "${ProjectName}-ObjectsBucketName"

  ObjectsBucketArn:
    Value: !GetAtt ObjectsBucket.Arn
    Export:
      Name: !Sub "${ProjectName}-ObjectsBucketArn"

  FrontendBucketName:
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${ProjectName}-FrontendBucketName"

  FrontendBucketArn:
    Value: !GetAtt FrontendBucket.Arn
    Export:
      Name: !Sub "${ProjectName}-FrontendBucketArn"
