AWSTemplateFormatVersion: "2010-09-09"
Description: >
  MyBookStore - Stack 06: S3 Buckets
  Bucket de objetos (portadas de libros) y bucket frontend (React build).
  OAC para acceso CloudFront a S3 sin credenciales publicas.

Parameters:
  ProjectName:
    Type: String
    Default: bookstore

Resources:

  # Bucket de objetos - portadas de libros
  ObjectsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-objects-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET]
            AllowedOrigins: ["*"]
            AllowedHeaders: ["*"]
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Sub "${ProjectName}-objects"

  # Bucket frontend - React build estatico
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-frontend-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Sub "${ProjectName}-frontend"

  # OAC para CloudFront - acceso seguro a S3 sin hacer bucket publico
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${ProjectName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Politica bucket frontend - solo CloudFront con OAC puede leer
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"

Outputs:
  ObjectsBucketName:
    Value: !Ref ObjectsBucket
    Export:
      Name: !Sub "${ProjectName}-ObjectsBucketName"

  ObjectsBucketArn:
    Value: !GetAtt ObjectsBucket.Arn
    Export:
      Name: !Sub "${ProjectName}-ObjectsBucketArn"

  FrontendBucketName:
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub "${ProjectName}-FrontendBucketName"

  FrontendBucketArn:
    Value: !GetAtt FrontendBucket.Arn
    Export:
      Name: !Sub "${ProjectName}-FrontendBucketArn"

  CloudFrontOACId:
    Value: !GetAtt CloudFrontOAC.Id
    Export:
      Name: !Sub "${ProjectName}-CloudFrontOACId"